FROM maven:3.6.3-jdk-11-slim AS build
WORKDIR /workspace/app

COPY pom.xml .
COPY src src

RUN mvn install -DskipTests

FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /workspace/app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]