FROM maven:3.6.3-jdk-8 AS build
WORKDIR /app
COPY src /app/src
COPY pom.xml /app
RUN mvn clean package

FROM openjdk:8-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/sample-0.0.1-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java", "-jar", "sample-0.0.1-SNAPSHOT.jar"]